version: '3'

services:
  comandaDB:
    image: postgres:14.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: comandaDB
    volumes:
      - ./postgres:/var/lib/postgresql/data
